# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalodevi.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1176, 667)
        Form.setStyleSheet("background-color: rgb(235, 236, 245);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1171, 651))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 0, 771, 611))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.rgbuygula = QtWidgets.QPushButton(self.groupBox_2)
        self.rgbuygula.setGeometry(QtCore.QRect(80, 80, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.rgbuygula.setFont(font)
        self.rgbuygula.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.rgbuygula.setObjectName("rgbuygula")
        self.cieuygula = QtWidgets.QPushButton(self.groupBox_2)
        self.cieuygula.setGeometry(QtCore.QRect(300, 80, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cieuygula.setFont(font)
        self.cieuygula.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.cieuygula.setObjectName("cieuygula")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(260, 140, 251, 351))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidgetcie = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidgetcie.setGeometry(QtCore.QRect(0, 30, 121, 271))
        self.listWidgetcie.setObjectName("listWidgetcie")
        self.gostercie = QtWidgets.QPushButton(self.groupBox_4)
        self.gostercie.setGeometry(QtCore.QRect(10, 310, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gostercie.setFont(font)
        self.gostercie.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gostercie.setObjectName("gostercie")
        self.ciegoster = QtWidgets.QLabel(self.groupBox_4)
        self.ciegoster.setGeometry(QtCore.QRect(130, 110, 111, 121))
        self.ciegoster.setText("")
        self.ciegoster.setObjectName("ciegoster")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(510, 140, 251, 351))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.hsvgoster = QtWidgets.QLabel(self.groupBox_5)
        self.hsvgoster.setGeometry(QtCore.QRect(130, 110, 111, 121))
        self.hsvgoster.setText("")
        self.hsvgoster.setObjectName("hsvgoster")
        self.listWidgethsv = QtWidgets.QListWidget(self.groupBox_5)
        self.listWidgethsv.setGeometry(QtCore.QRect(0, 30, 121, 271))
        self.listWidgethsv.setObjectName("listWidgethsv")
        self.gosterhsv = QtWidgets.QPushButton(self.groupBox_5)
        self.gosterhsv.setGeometry(QtCore.QRect(10, 310, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gosterhsv.setFont(font)
        self.gosterhsv.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gosterhsv.setObjectName("gosterhsv")
        self.hsvuygula = QtWidgets.QPushButton(self.groupBox_2)
        self.hsvuygula.setGeometry(QtCore.QRect(540, 80, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.hsvuygula.setFont(font)
        self.hsvuygula.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.hsvuygula.setObjectName("hsvuygula")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 140, 251, 351))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.listWidgetrgb = QtWidgets.QListWidget(self.groupBox_7)
        self.listWidgetrgb.setGeometry(QtCore.QRect(0, 30, 121, 271))
        self.listWidgetrgb.setObjectName("listWidgetrgb")
        self.gosterrgb = QtWidgets.QPushButton(self.groupBox_7)
        self.gosterrgb.setGeometry(QtCore.QRect(20, 310, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gosterrgb.setFont(font)
        self.gosterrgb.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gosterrgb.setObjectName("gosterrgb")
        self.rgbgoster = QtWidgets.QLabel(self.groupBox_7)
        self.rgbgoster.setGeometry(QtCore.QRect(130, 110, 111, 121))
        self.rgbgoster.setText("")
        self.rgbgoster.setObjectName("rgbgoster")
        self.bilgilendirme = QtWidgets.QLabel(self.groupBox_2)
        self.bilgilendirme.setGeometry(QtCore.QRect(140, 510, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.bilgilendirme.setFont(font)
        self.bilgilendirme.setText("")
        self.bilgilendirme.setObjectName("bilgilendirme")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 10, 371, 601))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label = QtWidgets.QLabel(self.groupBox_6)
        self.label.setGeometry(QtCore.QRect(20, 30, 221, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(10, 120, 341, 461))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.secilenorijinal = QtWidgets.QLabel(self.groupBox)
        self.secilenorijinal.setGeometry(QtCore.QRect(150, 40, 191, 191))
        self.secilenorijinal.setText("")
        self.secilenorijinal.setObjectName("secilenorijinal")
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 121, 241))
        self.listWidget.setObjectName("listWidget")
        self.goster = QtWidgets.QPushButton(self.groupBox)
        self.goster.setGeometry(QtCore.QRect(30, 280, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.goster.setFont(font)
        self.goster.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.goster.setObjectName("goster")
        self.verisetisec = QtWidgets.QPushButton(self.groupBox_6)
        self.verisetisec.setGeometry(QtCore.QRect(40, 60, 93, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.verisetisec.setFont(font)
        self.verisetisec.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.verisetisec.setObjectName("verisetisec")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 1141, 541))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_8.setGeometry(QtCore.QRect(0, 20, 551, 401))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.sift = QtWidgets.QPushButton(self.groupBox_8)
        self.sift.setGeometry(QtCore.QRect(50, 40, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sift.setFont(font)
        self.sift.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.sift.setObjectName("sift")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_8)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 100, 95, 281))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox_8)
        self.listWidget_3.setGeometry(QtCore.QRect(110, 100, 95, 281))
        self.listWidget_3.setObjectName("listWidget_3")
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_8)
        self.listWidget_4.setGeometry(QtCore.QRect(200, 100, 95, 281))
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setGeometry(QtCore.QRect(310, 140, 221, 221))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gostersift = QtWidgets.QPushButton(self.groupBox_8)
        self.gostersift.setGeometry(QtCore.QRect(370, 110, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gostersift.setFont(font)
        self.gostersift.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gostersift.setObjectName("gostersift")
        self.label_3 = QtWidgets.QLabel(self.groupBox_8)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(110, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(200, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_9.setGeometry(QtCore.QRect(560, 30, 551, 401))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.orb = QtWidgets.QPushButton(self.groupBox_9)
        self.orb.setGeometry(QtCore.QRect(50, 40, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.orb.setFont(font)
        self.orb.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.orb.setObjectName("orb")
        self.listWidget_5 = QtWidgets.QListWidget(self.groupBox_9)
        self.listWidget_5.setGeometry(QtCore.QRect(20, 100, 95, 281))
        self.listWidget_5.setObjectName("listWidget_5")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_9)
        self.listWidget_6.setGeometry(QtCore.QRect(110, 100, 95, 281))
        self.listWidget_6.setObjectName("listWidget_6")
        self.listWidget_7 = QtWidgets.QListWidget(self.groupBox_9)
        self.listWidget_7.setGeometry(QtCore.QRect(200, 100, 95, 281))
        self.listWidget_7.setObjectName("listWidget_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_9)
        self.label_6.setGeometry(QtCore.QRect(310, 140, 221, 221))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gosterorb = QtWidgets.QPushButton(self.groupBox_9)
        self.gosterorb.setGeometry(QtCore.QRect(370, 110, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gosterorb.setFont(font)
        self.gosterorb.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gosterorb.setObjectName("gosterorb")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_9)
        self.label_8.setGeometry(QtCore.QRect(110, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_9)
        self.label_9.setGeometry(QtCore.QRect(200, 80, 55, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_23 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_23.setGeometry(QtCore.QRect(150, 30, 121, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_13.setFont(font)
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_23)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 50, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_14.setFont(font)
        self.radioButton_14.setObjectName("radioButton_14")
        self.modelgiris = QtWidgets.QPushButton(self.tab_3)
        self.modelgiris.setGeometry(QtCore.QRect(80, 140, 211, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modelgiris.setFont(font)
        self.modelgiris.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.modelgiris.setObjectName("modelgiris")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 30, 121, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 30, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 50, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 70, 95, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_12.setGeometry(QtCore.QRect(270, 30, 121, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_10.setGeometry(QtCore.QRect(390, 30, 211, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 81, 41))
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 30, 61, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gerceklestir = QtWidgets.QPushButton(self.tab_3)
        self.gerceklestir.setGeometry(QtCore.QRect(460, 140, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gerceklestir.setFont(font)
        self.gerceklestir.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gerceklestir.setObjectName("gerceklestir")
        self.tableView = QtWidgets.QTableView(self.tab_3)
        self.tableView.setGeometry(QtCore.QRect(20, 260, 281, 141))
        self.tableView.setObjectName("tableView")
        self.tableView_2 = QtWidgets.QTableView(self.tab_3)
        self.tableView_2.setGeometry(QtCore.QRect(320, 430, 191, 141))
        self.tableView_2.setObjectName("tableView_2")
        self.tableView_3 = QtWidgets.QTableView(self.tab_3)
        self.tableView_3.setGeometry(QtCore.QRect(20, 430, 281, 141))
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_4 = QtWidgets.QTableView(self.tab_3)
        self.tableView_4.setGeometry(QtCore.QRect(310, 260, 191, 141))
        self.tableView_4.setObjectName("tableView_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(520, 270, 81, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gosterkfold = QtWidgets.QPushButton(self.tab_3)
        self.gosterkfold.setGeometry(QtCore.QRect(530, 320, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gosterkfold.setFont(font)
        self.gosterkfold.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.gosterkfold.setObjectName("gosterkfold")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(780, 70, 280, 280))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_13.setGeometry(QtCore.QRect(0, 0, 391, 621))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.modelegitim = QtWidgets.QPushButton(self.groupBox_13)
        self.modelegitim.setGeometry(QtCore.QRect(80, 30, 161, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modelegitim.setFont(font)
        self.modelegitim.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.modelegitim.setObjectName("modelegitim")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 40, 51, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_13)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 55, 16))
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_13)
        self.label_16.setGeometry(QtCore.QRect(20, 350, 311, 251))
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_20 = QtWidgets.QLabel(self.groupBox_13)
        self.label_20.setGeometry(QtCore.QRect(20, 100, 311, 251))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_13 = QtWidgets.QLabel(self.groupBox_13)
        self.label_13.setGeometry(QtCore.QRect(250, 20, 131, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_14.setGeometry(QtCore.QRect(390, 0, 751, 621))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.tableView_5 = QtWidgets.QTableView(self.groupBox_14)
        self.tableView_5.setGeometry(QtCore.QRect(20, 30, 431, 241))
        self.tableView_5.setObjectName("tableView_5")
        self.modeltest = QtWidgets.QPushButton(self.groupBox_14)
        self.modeltest.setGeometry(QtCore.QRect(460, 30, 161, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modeltest.setFont(font)
        self.modeltest.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.modeltest.setObjectName("modeltest")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setGeometry(QtCore.QRect(20, 280, 431, 271))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_17 = QtWidgets.QLabel(self.groupBox_15)
        self.label_17.setGeometry(QtCore.QRect(30, 40, 291, 41))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_15)
        self.label_18.setGeometry(QtCore.QRect(30, 90, 291, 41))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_15)
        self.label_19.setGeometry(QtCore.QRect(30, 160, 291, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_34 = QtWidgets.QLabel(self.groupBox_14)
        self.label_34.setGeometry(QtCore.QRect(460, 180, 251, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_16 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 10, 1141, 611))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_17.setGeometry(QtCore.QRect(30, 30, 351, 581))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.resimsecvgg = QtWidgets.QPushButton(self.groupBox_17)
        self.resimsecvgg.setGeometry(QtCore.QRect(110, 20, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resimsecvgg.setFont(font)
        self.resimsecvgg.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.resimsecvgg.setObjectName("resimsecvgg")
        self.label_11 = QtWidgets.QLabel(self.groupBox_17)
        self.label_11.setGeometry(QtCore.QRect(19, 250, 311, 250))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_17)
        self.label_12.setGeometry(QtCore.QRect(40, 520, 250, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_21 = QtWidgets.QLabel(self.groupBox_17)
        self.label_21.setGeometry(QtCore.QRect(10, 180, 211, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_17)
        self.label_22.setGeometry(QtCore.QRect(10, 150, 341, 31))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_17)
        self.label_23.setGeometry(QtCore.QRect(110, 60, 91, 91))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.groupBox_18 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_18.setGeometry(QtCore.QRect(410, 30, 351, 581))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.resimsecresnet = QtWidgets.QPushButton(self.groupBox_18)
        self.resimsecresnet.setGeometry(QtCore.QRect(110, 20, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resimsecresnet.setFont(font)
        self.resimsecresnet.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.resimsecresnet.setObjectName("resimsecresnet")
        self.label_24 = QtWidgets.QLabel(self.groupBox_18)
        self.label_24.setGeometry(QtCore.QRect(19, 250, 311, 250))
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.groupBox_18)
        self.label_25.setGeometry(QtCore.QRect(40, 520, 250, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_18)
        self.label_26.setGeometry(QtCore.QRect(10, 180, 211, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_18)
        self.label_27.setGeometry(QtCore.QRect(10, 150, 341, 31))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_18)
        self.label_28.setGeometry(QtCore.QRect(110, 60, 91, 91))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setGeometry(QtCore.QRect(780, 30, 351, 581))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.resimsecinception = QtWidgets.QPushButton(self.groupBox_19)
        self.resimsecinception.setGeometry(QtCore.QRect(110, 20, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resimsecinception.setFont(font)
        self.resimsecinception.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);")
        self.resimsecinception.setObjectName("resimsecinception")
        self.label_29 = QtWidgets.QLabel(self.groupBox_19)
        self.label_29.setGeometry(QtCore.QRect(19, 250, 311, 250))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_19)
        self.label_30.setGeometry(QtCore.QRect(40, 520, 250, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setText("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_19)
        self.label_31.setGeometry(QtCore.QRect(10, 180, 211, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_19)
        self.label_32.setGeometry(QtCore.QRect(10, 150, 341, 31))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_19)
        self.label_33.setGeometry(QtCore.QRect(110, 60, 91, 91))
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Renk Uzayları"))
        self.rgbuygula.setText(_translate("Form", "RGB UYGULA"))
        self.cieuygula.setText(_translate("Form", "CIE UYGULA"))
        self.groupBox_4.setTitle(_translate("Form", "Seçilen Verisetinden Görüntüler"))
        self.gostercie.setText(_translate("Form", "GÖSTER"))
        self.groupBox_5.setTitle(_translate("Form", "Seçilen Verisetinden Görüntüler"))
        self.gosterhsv.setText(_translate("Form", "GÖSTER"))
        self.hsvuygula.setText(_translate("Form", "HSV UYGULA"))
        self.groupBox_7.setTitle(_translate("Form", "Seçilen Verisetinden Görüntüler"))
        self.gosterrgb.setText(_translate("Form", "GÖSTER"))
        self.groupBox_6.setTitle(_translate("Form", "Veri Seti Seçme"))
        self.label.setText(_translate("Form", "İşlenecek Verisetini Seçiniz:"))
        self.groupBox.setTitle(_translate("Form", "Seçilen Verisetinden Görüntüler"))
        self.goster.setText(_translate("Form", "GÖSTER"))
        self.verisetisec.setText(_translate("Form", "Klasör Seçiniz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Görüntü Alma-Çevirme İşlemleri"))
        self.groupBox_3.setTitle(_translate("Form", "Keypoint ALgoritmaları"))
        self.groupBox_8.setTitle(_translate("Form", "SIFT"))
        self.sift.setText(_translate("Form", "SIFT ALGORİTMASI UYGULA"))
        self.gostersift.setText(_translate("Form", "GÖSTER"))
        self.label_3.setText(_translate("Form", "RGB"))
        self.label_4.setText(_translate("Form", "CIE"))
        self.label_5.setText(_translate("Form", "HSV"))
        self.groupBox_9.setTitle(_translate("Form", "ORB"))
        self.orb.setText(_translate("Form", "ORB ALGORİTMASI UYGULA"))
        self.gosterorb.setText(_translate("Form", "GÖSTER"))
        self.label_7.setText(_translate("Form", "RGB"))
        self.label_8.setText(_translate("Form", "CIE"))
        self.label_9.setText(_translate("Form", "HSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Keypoint Tespiti"))
        self.groupBox_23.setTitle(_translate("Form", "Keypoint Yöntemi"))
        self.radioButton_13.setText(_translate("Form", "SIFT"))
        self.radioButton_14.setText(_translate("Form", "ORB"))
        self.modelgiris.setText(_translate("Form", "GİRİŞ GÖRÜNTÜLERİNİ OLUŞTUR"))
        self.groupBox_11.setTitle(_translate("Form", "Renk Uzayı"))
        self.radioButton_4.setText(_translate("Form", "RGB"))
        self.radioButton_5.setText(_translate("Form", "HSV"))
        self.radioButton_6.setText(_translate("Form", "CIE"))
        self.groupBox_12.setTitle(_translate("Form", "nxn bilgisi"))
        self.groupBox_10.setTitle(_translate("Form", "Ayırma"))
        self.comboBox.setCurrentText(_translate("Form", "KFold"))
        self.comboBox.setItemText(0, _translate("Form", "KFold"))
        self.comboBox.setItemText(1, _translate("Form", "Holdout"))
        self.gerceklestir.setText(_translate("Form", "GERÇEKLEŞTİR"))
        self.gosterkfold.setText(_translate("Form", "GÖSTER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Model İşlemleri"))
        self.groupBox_13.setTitle(_translate("Form", "Model Eğitimi"))
        self.modelegitim.setText(_translate("Form", "MODEL EĞİTİMİNE BAŞLA"))
        self.label_14.setText(_translate("Form", "Epoch"))
        self.groupBox_14.setTitle(_translate("Form", "Model Testi"))
        self.modeltest.setText(_translate("Form", "MODEL TESTİ--TAHMİN"))
        self.groupBox_15.setTitle(_translate("Form", "Tahmin Sonuçları"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Model İşlemleri"))
        self.groupBox_16.setTitle(_translate("Form", "Transfer Learning Modelleri"))
        self.groupBox_17.setTitle(_translate("Form", "VGG16"))
        self.resimsecvgg.setText(_translate("Form", "RESİM SEÇ"))
        self.groupBox_18.setTitle(_translate("Form", "RESNET50"))
        self.resimsecresnet.setText(_translate("Form", "RESİM SEÇ"))
        self.groupBox_19.setTitle(_translate("Form", "INCEPTIONV3"))
        self.resimsecinception.setText(_translate("Form", "RESİM SEÇ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Transfer Learning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
